variables: 
  DOCKER_HOST: tcp://docker:2376/

image:
  name: docker/compose:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  before_script:
    - docker version
    - docker-compose version
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up
