variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

image:
  name: docker/compose:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up
