image:
  name: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  before_script:
    - apk add --update python3 py-pip python3-dev && pip install docker-compose # install docker-compose
    - docker version
    - docker-compose version
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up
