image:
  name: docker:20.10.16

services:
  - docker:20.10.16-dind

stages:
  - build

build:
  stage: build
  before_script:
    - docker version
    - curl -L "https://github.com/docker/compose/releases/download/1.10.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - export PATH=/usr/local/bin:$PATH
    - docker-compose version
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up
