stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: nexus:443/docker/compose
  variables:
    COMPOSE_HTTP_TIMEOUT: 180
  before_script:
    - docker info
    - docker-compose version
  script:
    - 'echo "10.27.95.5 nexus" >>/etc/hosts'
    - docker-compose down || true
    - docker rm -f ipsclient_srv || true
    - docker-compose up -d
    - |+
      i=1
      while [ True ]; do
        sleep 1
        docker logs ipsclient_srv 2>&1 | grep "Uvicorn running on" >/dev/null && break
        let i=i+1
        [[ $i -gt 45 ]] && break
      done
    - docker logs ipsclient_srv 2>&1 | grep "Uvicorn running on"
    - docker-compose down

deploy:
  stage: deploy
  only:
    - main
  image:
    name: nexus:443/netpardaz/ubuntu-ansible:20.04
  script:
    - tar czf /home/ansible/app.tar.gz . && cp playbook.yml clientapi.service 00-clientapi.conf clientapisrv /home/ansible
    - sudo -u ansible -s /bin/bash -c "mkdir /home/ansible/inventory; echo ics-sec ansible_host=10.27.95.1 ansible_ssh_user=ansible ansible_become_pass=`echo $ANSIBLE_PASSWORD | base64 -d` >/home/ansible/inventory/hosts"
    - echo $ANSIBLE_PRIVATE_KEY | base64 -d > /home/ansible/.ssh/id_rsa; chown ansible:ansible /home/ansible/.ssh/id_rsa; chmod 0600 /home/ansible/.ssh/id_rsa
    - /usr/bin/ssh-keygen -f /home/ansible/.ssh/id_rsa -y > /home/ansible/.ssh/id_rsa.pub
    - export ANSIBLE_HOST_KEY_CHECKING=False; /home/ansible/.local/bin/ansible-playbook /home/ansible/playbook.yml -i /home/ansible/inventory/hosts


