image:
  name: nexus:443/docker/compose

stages:
  - build

build:
  stage: build
  variables:
    COMPOSE_HTTP_TIMEOUT: 180
  before_script:
    - docker info
    - docker-compose version
  script:
    - 'echo "10.27.95.5 nexus" >>/etc/hosts'
    - cat Dockerfile
    - docker-compose down || true
    - docker rm -f ipsclient_srv || true
    - docker rmi -f ips_client:latest || true
    - docker-compose up
