image:
  name: docker/compose:latest

stages:
  - build

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH != "stage"'
  script:
    - docker-compose down
    - docker-compose build
    - docker-compose up
