version: '3.7'
services:
  psql:
      container_name: postgres_database
      image: postgres
      environment:
          - POSTGRES_PASSWORD=S0mETh1nGV3ryC0mPl3x
          - IPS_CLIENT_POSTGRES_USER=postgres
          - IPS_CLIENT_POSTGRES_PASSWORD=postgres
          - IPS_CLIENT_POSTGRES_DB=ips_client
      restart: unless-stopped
  ips_client:
      build: .
      container_name: ips_client_srv
      restart: always
      environment:
          - IPS_CLIENT_POSTGRES_NAME=ips_client
          - IPS_CLIENT_POSTGRES_USER=postgres
          - IPS_CLIENT_POSTGRES_HOST=psql
          - IPS_CLIENT_POSTGRES_PORT=5432
          - IPS_CLIENT_POSTGRES_PASSWORD=postgres
          - IPS_CLIENT_IPS_SERVER_URL=http://192.168.1.56:8000
          - IPS_CLIENT_SNORT_RULES_PATH=/etc/snort/rules/
          - IPS_CLIENT_SNORT_CONF_PATH=/etc/snort/snort.conf
      ports:
          - "8000:8000"  
      command: make run
      depends_on:
        - psql
